// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK02kMyp-4myW_atHem4rOneWXhzIjG5g',
    appId: '1:315444647376:web:cd023a01e0902733f415d5',
    messagingSenderId: '315444647376',
    projectId: 'awsb-ca142',
    authDomain: 'awsb-ca142.firebaseapp.com',
    storageBucket: 'awsb-ca142.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD16mw6kM-HTpmThob-lSu0MFJWaRvWI_k',
    appId: '1:315444647376:android:5bce25fe1e967dbef415d5',
    messagingSenderId: '315444647376',
    projectId: 'awsb-ca142',
    storageBucket: 'awsb-ca142.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWFhZQcy_gdS4pfuJYrKKD9QxR-xK0Dp0',
    appId: '1:315444647376:ios:a5a3e6694ef42f84f415d5',
    messagingSenderId: '315444647376',
    projectId: 'awsb-ca142',
    storageBucket: 'awsb-ca142.appspot.com',
    iosBundleId: 'com.example.auctionwesbank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWFhZQcy_gdS4pfuJYrKKD9QxR-xK0Dp0',
    appId: '1:315444647376:ios:a5a3e6694ef42f84f415d5',
    messagingSenderId: '315444647376',
    projectId: 'awsb-ca142',
    storageBucket: 'awsb-ca142.appspot.com',
    iosBundleId: 'com.example.auctionwesbank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK02kMyp-4myW_atHem4rOneWXhzIjG5g',
    appId: '1:315444647376:web:ddd05a704c6d1a1af415d5',
    messagingSenderId: '315444647376',
    projectId: 'awsb-ca142',
    authDomain: 'awsb-ca142.firebaseapp.com',
    storageBucket: 'awsb-ca142.appspot.com',
  );
}
